// Roda os testes de navegador que não dependem de configuração do tutor.
// Precisa do jogo no ar (npm run dev ou npm start) em URL_JOGO (padrão :3000).
// PARALELO=n roda n arquivos ao mesmo tempo (padrão 1, um atrás do outro).
// Os que medem desempenho (SOZINHOS) rodam no fim, um de cada vez e sem
// ninguém em paralelo: com outros testes disputando o processador, a medida
// vira ruído.
// FILTRO=regex roda só os testes cuja linha ("arquivo argumentos") casa com ela.
import { spawn } from "node:child_process";

const TESTES = [
  ["tutor-apresentacao.mjs", "desktop"],
  ["tutor-apresentacao.mjs", "retrato"],
  ["tutor-apresentacao.mjs", "paisagem"],
  ["portas-museu.mjs", "desktop"],
  ["portas-museu.mjs", "retrato"],
  ["portas-museu.mjs", "paisagem"],
  ["duplo-toque-u4.mjs", "desktop"],
  ["duplo-toque-u4.mjs", "retrato"],
  ["duplo-toque-u4.mjs", "paisagem"],
  ["falas.mjs", "desktop"],
  ["falas.mjs", "retrato"],
  ["falas.mjs", "paisagem"],
  ["museu.mjs", "desktop"],
  ["museu.mjs", "retrato"],
  ["museu.mjs", "paisagem"],
  ["depuracao-cena-bloqueio.mjs", "desktop"],
  ["depuracao-cena-bloqueio.mjs", "retrato"],
  ["depuracao-cena-bloqueio.mjs", "paisagem"],
  ["depuracao.mjs", "desktop", "4"],
  ["depuracao.mjs", "retrato", "4"],
  ["depuracao.mjs", "paisagem", "4"],
  ["chamados.mjs", "desktop", "6"],
  ["chamados.mjs", "retrato", "6"],
  ["chamados.mjs", "paisagem", "6"],
  ["chamados.mjs", "desktop", "5"],
  ["chamados.mjs", "retrato", "5"],
  ["chamados.mjs", "paisagem", "5"],
  ["depuracao.mjs", "desktop", "3"],
  ["depuracao.mjs", "retrato", "3"],
  ["depuracao.mjs", "paisagem", "3"],
  ["depuracao.mjs", "desktop", "2"],
  ["depuracao.mjs", "retrato", "2"],
  ["depuracao.mjs", "paisagem", "2"],
  ["depuracao.mjs", "desktop", "1"],
  ["depuracao.mjs", "retrato", "1"],
  ["depuracao.mjs", "paisagem", "1"],
  ["estruturas-zona.mjs", "desktop", "4"],
  ["estruturas-zona.mjs", "retrato", "4"],
  ["estruturas-zona.mjs", "paisagem", "4"],
  ["estruturas-zona.mjs", "desktop", "3"],
  ["estruturas-zona.mjs", "retrato", "3"],
  ["estruturas-zona.mjs", "paisagem", "3"],
  ["estruturas-zona.mjs", "desktop", "2"],
  ["estruturas-zona.mjs", "retrato", "2"],
  ["estruturas-zona.mjs", "paisagem", "2"],
  ["estruturas-zona.mjs", "desktop", "1"],
  ["estruturas-zona.mjs", "retrato", "1"],
  ["estruturas-zona.mjs", "paisagem", "1"],
  ["cenas-novas.mjs", "desktop"],
  ["cenas-novas.mjs", "retrato"],
  ["cenas-novas.mjs", "paisagem"],
  ["algoritmos.mjs", "desktop", "4"],
  ["algoritmos.mjs", "retrato", "4"],
  ["algoritmos.mjs", "paisagem", "4"],
  ["algoritmos.mjs", "desktop", "3"],
  ["algoritmos.mjs", "retrato", "3"],
  ["algoritmos.mjs", "paisagem", "3"],
  ["algoritmos.mjs", "desktop", "2"],
  ["algoritmos.mjs", "retrato", "2"],
  ["algoritmos.mjs", "paisagem", "2"],
  ["algoritmos.mjs", "desktop", "1"],
  ["algoritmos.mjs", "retrato", "1"],
  ["algoritmos.mjs", "paisagem", "1"],
  ["resolvendo.mjs", "desktop", "4"],
  ["resolvendo.mjs", "retrato", "4"],
  ["resolvendo.mjs", "paisagem", "4"],
  ["resolvendo.mjs", "desktop", "3"],
  ["resolvendo.mjs", "retrato", "3"],
  ["resolvendo.mjs", "paisagem", "3"],
  ["resolvendo.mjs", "desktop", "2"],
  ["resolvendo.mjs", "retrato", "2"],
  ["resolvendo.mjs", "paisagem", "2"],
  ["resolvendo.mjs", "desktop", "1"],
  ["resolvendo.mjs", "retrato", "1"],
  ["resolvendo.mjs", "paisagem", "1"],
  ["listas.mjs", "desktop", "logica-listas-e-objetos-u4"],
  ["listas.mjs", "retrato", "logica-listas-e-objetos-u4"],
  ["listas.mjs", "paisagem", "logica-listas-e-objetos-u4"],

  ["listas.mjs", "desktop", "logica-listas-e-objetos-u3"],
  ["listas.mjs", "retrato", "logica-listas-e-objetos-u3"],
  ["listas.mjs", "paisagem", "logica-listas-e-objetos-u3"],

  ["listas.mjs", "desktop", "logica-listas-e-objetos-u2"],
  ["listas.mjs", "retrato", "logica-listas-e-objetos-u2"],
  ["listas.mjs", "paisagem", "logica-listas-e-objetos-u2"],

  ["listas.mjs", "desktop", "logica-listas-e-objetos-u1"],
  ["listas.mjs", "retrato", "logica-listas-e-objetos-u1"],
  ["listas.mjs", "paisagem", "logica-listas-e-objetos-u1"],

  ["funcoes.mjs", "desktop", "logica-funcoes-u4"],
  ["funcoes.mjs", "retrato", "logica-funcoes-u4"],
  ["funcoes.mjs", "paisagem", "logica-funcoes-u4"],
  ["funcoes.mjs", "desktop", "logica-funcoes-u3"],
  ["funcoes.mjs", "retrato", "logica-funcoes-u3"],
  ["funcoes.mjs", "paisagem", "logica-funcoes-u3"],
  ["funcoes.mjs", "desktop", "logica-funcoes-u2"],
  ["funcoes.mjs", "retrato", "logica-funcoes-u2"],
  ["funcoes.mjs", "paisagem", "logica-funcoes-u2"],
  ["funcoes.mjs", "desktop", "logica-funcoes-u1"],
  ["funcoes.mjs", "retrato", "logica-funcoes-u1"],
  ["funcoes.mjs", "paisagem", "logica-funcoes-u1"],
  ["tela-cheia.mjs", "desktop"],
  ["tela-cheia.mjs", "retrato"],
  ["tela-cheia.mjs", "paisagem"],
  ["sincronia.mjs"],
  ["ferramentas.mjs"],
  ["fase-completa.mjs", "desktop"],
  ["fase-completa.mjs", "retrato"],
  ["fase-completa.mjs", "paisagem"],
  ["movel.mjs"],
  ["ferramentas-novas.mjs"],
  ["apresentacao-movimento.mjs"],
  ["unidades.mjs", "desktop"],
  ["unidades.mjs", "retrato"],
  ["unidades.mjs", "paisagem"],
  ["renomear-links.mjs"],
  ["css.mjs"],
  ["estilos.mjs"],
  ["calculado.mjs"],
  ["documento.mjs"],
  ["variaveis.mjs", "desktop"],
  ["variaveis.mjs", "retrato"],
  ["variaveis.mjs", "paisagem"],
  ["tema.mjs", "desktop"],
  ["tema.mjs", "retrato"],
  ["tema.mjs", "paisagem"],
  ["dispositivo.mjs", "desktop"],
  ["dispositivo.mjs", "retrato"],
  ["dispositivo.mjs", "paisagem"],
  ["lighthouse.mjs", "desktop"],
  ["lighthouse.mjs", "retrato"],
  ["lighthouse.mjs", "paisagem"],
  ["publicar.mjs", "desktop"],
  ["publicar.mjs", "retrato"],
  ["publicar.mjs", "paisagem"],
  ["layout.mjs", "desktop"],
  ["layout.mjs", "retrato"],
  ["layout.mjs", "paisagem"],
  ["mapa.mjs", "desktop"],
  ["mapa.mjs", "retrato"],
  ["mapa.mjs", "paisagem"],
  ["mundo.mjs", "desktop"],
  ["mundo.mjs", "retrato"],
  ["mundo.mjs", "paisagem"],
  ["explorar.mjs", "desktop"],
  ["explorar.mjs", "retrato"],
  ["explorar.mjs", "paisagem"],
  ["busca.mjs", "desktop"],
  ["busca.mjs", "retrato"],
  ["busca.mjs", "paisagem"],
  ["ser-encontrado.mjs", "desktop"],
  ["ser-encontrado.mjs", "retrato"],
  ["ser-encontrado.mjs", "paisagem"],
  ["campanha.mjs", "desktop"],
  ["campanha.mjs", "retrato"],
  ["campanha.mjs", "paisagem"],
  ["revisao.mjs", "desktop"],
  ["revisao.mjs", "retrato"],
  ["revisao.mjs", "paisagem"],
  ["console.mjs", "desktop"],
  ["console.mjs", "retrato"],
  ["console.mjs", "paisagem"],
  ["palco.mjs", "desktop"],
  ["palco.mjs", "retrato"],
  ["palco.mjs", "paisagem"],
  ["circuito.mjs", "desktop"],
  ["circuito.mjs", "retrato"],
  ["circuito.mjs", "paisagem"],
  ["ponte-circuito.mjs", "desktop"],
  ["ponte-circuito.mjs", "retrato"],
  ["ponte-circuito.mjs", "paisagem"],
  ["depurador.mjs", "desktop"],
  ["depurador.mjs", "retrato"],
  ["depurador.mjs", "paisagem"],
  ["ordenar.mjs", "desktop"],
  ["ordenar.mjs", "retrato"],
  ["ordenar.mjs", "paisagem"],
  ["resolver.mjs", "desktop"],
  ["resolver.mjs", "retrato"],
  ["resolver.mjs", "paisagem"],
  ["cenas.mjs", "desktop"],
  ["cenas.mjs", "retrato"],
  ["cenas.mjs", "paisagem"],
  ["contrato.mjs", "desktop"],
  ["contrato.mjs", "retrato"],
  ["contrato.mjs", "paisagem"],
  ["contrato-logica.mjs", "desktop"],
  ["contrato-logica.mjs", "retrato"],
  ["contrato-logica.mjs", "paisagem"],
  ["estruturas.mjs", "desktop"],
  ["estruturas.mjs", "retrato"],
  ["estruturas.mjs", "paisagem"],
  ["apresentacoes-logica.mjs", "desktop"],
  ["apresentacoes-logica.mjs", "retrato"],
  ["apresentacoes-logica.mjs", "paisagem"],
  ["logica.mjs", "desktop"],
  ["logica.mjs", "retrato"],
  ["logica.mjs", "paisagem"],
  ["primeiros-comandos.mjs", "desktop", "logica-primeiros-comandos-u2"],
  ["primeiros-comandos.mjs", "retrato", "logica-primeiros-comandos-u2"],
  ["primeiros-comandos.mjs", "paisagem", "logica-primeiros-comandos-u2"],
  ["primeiros-comandos.mjs", "desktop", "logica-primeiros-comandos-u3"],
  ["primeiros-comandos.mjs", "retrato", "logica-primeiros-comandos-u3"],
  ["primeiros-comandos.mjs", "paisagem", "logica-primeiros-comandos-u3"],
  ["decisoes.mjs", "desktop", "logica-decisoes-u1"],
  ["decisoes.mjs", "retrato", "logica-decisoes-u1"],
  ["decisoes.mjs", "paisagem", "logica-decisoes-u1"],
  ["decisoes.mjs", "desktop", "logica-decisoes-u2"],
  ["decisoes.mjs", "retrato", "logica-decisoes-u2"],
  ["decisoes.mjs", "paisagem", "logica-decisoes-u2"],
  ["decisoes.mjs", "desktop", "logica-decisoes-u3"],
  ["decisoes.mjs", "retrato", "logica-decisoes-u3"],
  ["decisoes.mjs", "paisagem", "logica-decisoes-u3"],
  ["decisoes.mjs", "desktop", "logica-decisoes-u4"],
  ["decisoes.mjs", "retrato", "logica-decisoes-u4"],
  ["decisoes.mjs", "paisagem", "logica-decisoes-u4"],
  ["retomar.mjs"],
  ["migracao.mjs"],
  ["audio.mjs"],
];

/** Medem desempenho: rodam no fim, sozinhos. */
const SOZINHOS = [["desempenho-mundo.mjs"]];

const PARALELO = Math.max(1, Number(process.env.PARALELO ?? 1));

/** Roda um arquivo; em paralelo, a saída de cada um sai inteira no fim, sem misturar. */
function rodar([arquivo, ...argumentos]) {
  return new Promise((resolver) => {
    const titulo = `\n# ${arquivo} ${argumentos.join(" ")}`;
    if (PARALELO === 1) console.log(titulo);
    const filho = spawn(process.execPath, [new URL(arquivo, import.meta.url).pathname, ...argumentos], {
      stdio: PARALELO === 1 ? "inherit" : "pipe",
    });
    let saida = "";
    filho.stdout?.on("data", (pedaco) => (saida += pedaco));
    filho.stderr?.on("data", (pedaco) => (saida += pedaco));
    filho.on("close", (codigo) => {
      if (PARALELO > 1) console.log(`${titulo}\n${saida.trimEnd()}`);
      resolver(codigo === 0);
    });
  });
}

const falhas = [];
const FILTRO = process.env.FILTRO ? new RegExp(process.env.FILTRO) : null;
const fila = TESTES.filter((teste) => !FILTRO || FILTRO.test(teste.join(" ")));
await Promise.all(
  Array.from({ length: PARALELO }, async () => {
    while (fila.length > 0) {
      const teste = fila.shift();
      if (!(await rodar(teste))) falhas.push(teste.join(" "));
    }
  }),
);
for (const teste of SOZINHOS.filter((item) => !FILTRO || FILTRO.test(item.join(" ")))) {
  if (!(await rodar(teste))) falhas.push(teste.join(" "));
}
console.log(falhas.length === 0 ? "\nTudo certo." : `\n${falhas.length} teste(s) falharam: ${falhas.join("; ")}`);
process.exit(falhas.length === 0 ? 0 : 1);
