/*
 * Revisão: os conceitos das salas 3 a 6 do Museu das Origens (rodada 38).
 * Como os das salas 1 e 2, previsões sobre uma vitrine pequena e própria
 * (a Revisão do dia não aceita a área exposicao). Dois por conceito, com
 * a resposta certa em lugares diferentes.
 */
import type { ItemRevisao } from "../tipos";
import { item, vitrine } from "./origens";

export const ITENS_ORIGENS_SALAS_3_A_6: readonly ItemRevisao[] = [
  // Sala 3: as linguagens.
  item(
    "sintaxe-1",
    "sintaxe",
    vitrine("vitrine-ola.exemplo", "O mesmo recado em duas linguagens", 'print("Olá") / console.log("Olá")'),
    {
      pergunta: "As duas linhas mostram Olá. O que muda entre elas?",
      opcoes: ["O resultado", "A sintaxe: o jeito de escrever", "O computador que roda"],
      correta: 1,
      explicacao: "As duas fazem a mesma coisa. Muda a escrita, a sintaxe de cada linguagem.",
    },
    { pergunta: "As duas mostram a mesma palavra?", dica: "Sintaxe é a gramática da linguagem: as palavras e os sinais." },
  ),
  item(
    "sintaxe-2",
    "sintaxe",
    vitrine("vitrine-somar.exemplo", "Somar 2 e 3 em três linguagens", "2 + 3 / 2 + 3 / ADD 2 TO 3"),
    {
      pergunta: "As três linhas somam 2 e 3. Quanto dá em cada uma?",
      opcoes: ["5 nas três", "Depende da linguagem", "Só a primeira soma"],
      correta: 0,
      explicacao: "A conta é a mesma em todas: 5. A sintaxe muda (até ADD, em inglês), o conceito não.",
    },
    { pergunta: "Somar muda de resultado conforme a escrita?", dica: "Conceito igual, escrita diferente." },
  ),
  item(
    "ferramenta-certa-1",
    "ferramenta-certa",
    vitrine("vitrine-planilha.exemplo", "Uma planilha com um milhão de vendas", "data | produto | valor"),
    {
      pergunta: "Para analisar essa planilha gigante, qual linguagem é a escolha mais comum hoje?",
      opcoes: ["COBOL", "BASIC", "Python"],
      correta: 2,
      explicacao: "Python virou a mais comum para dados: tem ferramentas prontas para tabelas e gráficos.",
    },
    { pergunta: "Qual linguagem ficou famosa com dados e IA?", dica: "É a da futura Ilha Python." },
  ),
  item(
    "ferramenta-certa-2",
    "ferramenta-certa",
    vitrine("vitrine-botao.exemplo", "Um botão que abre um menu na página", "[ Menu ]"),
    {
      pergunta: "Para o menu abrir no navegador, sem instalar nada, qual linguagem roda ali?",
      opcoes: ["JavaScript", "COBOL", "C"],
      correta: 0,
      explicacao: "Todo navegador roda JavaScript sozinho. Por isso ele é a linguagem das páginas que reagem.",
    },
    { pergunta: "Qual linguagem todo navegador já roda?", dica: "É a da Ilha Lógica." },
  ),
  item(
    "indentacao-1",
    "indentacao",
    vitrine("vitrine-recuo.exemplo", "Um laço em Python", "for i in range(3):<br>    print(i)"),
    {
      pergunta: "No Python, como ele sabe que o print fica dentro do laço?",
      opcoes: ["Pelas chaves { }", "Pelo recuo: os espaços na frente", "Pelo ponto e vírgula"],
      correta: 1,
      explicacao: "O Python não usa chaves para isso: o recuo (a indentação) diz o que está dentro.",
    },
    { pergunta: "O que tem na frente do print?", dica: "Os espaços no começo da linha fazem diferença no Python." },
  ),
  item(
    "indentacao-2",
    "indentacao",
    vitrine("vitrine-sem-recuo.exemplo", "O mesmo laço, sem os espaços", "for i in range(3):<br>print(i)"),
    {
      pergunta: "Sem os espaços antes do print, o que o Python faz?",
      opcoes: ["Roda igual", "Mostra só o último número", "Reclama: falta o recuo do bloco"],
      correta: 2,
      explicacao: "Ele dá IndentationError: depois dos dois-pontos, o Python espera uma linha recuada.",
    },
    { pergunta: "Depois dos dois-pontos, o Python espera o quê?", dica: "Um bloco recuado." },
  ),
  item(
    "compilador-1",
    "compilador",
    vitrine("vitrine-executavel.exemplo", "Um programa já compilado", "jogo.exe"),
    {
      pergunta: "Esse programa já foi compilado. Para rodar de novo amanhã, ele precisa ser traduzido outra vez?",
      opcoes: ["Não: já está pronto em linguagem de máquina", "Sim, toda vez", "Só se a internet cair"],
      correta: 0,
      explicacao: "O compilador traduz tudo antes e entrega o programa pronto. Rodar de novo não precisa de tradução.",
    },
    { pergunta: "O que o compilador entrega no fim?", dica: "Um programa pronto, em bits." },
  ),
  item(
    "compilador-2",
    "compilador",
    vitrine("vitrine-tradutor.exemplo", "Um livro traduzido inteiro antes de ser vendido", "LIVRO TRADUZIDO"),
    {
      pergunta: "Traduzir o livro todo antes, e só então ler, parece qual tradutor de programas?",
      opcoes: ["O intérprete", "O compilador", "Nenhum dos dois"],
      correta: 1,
      explicacao: "O compilador faz assim: traduz o programa inteiro antes de rodar.",
    },
    { pergunta: "Quem traduz tudo antes?", dica: "O que entrega o programa pronto." },
  ),
  item(
    "interpretador-1",
    "interpretador",
    vitrine("vitrine-interprete.exemplo", "Uma conversa com intérprete ao lado", "frase... tradução... frase... tradução..."),
    {
      pergunta: "Traduzir frase por frase, enquanto a conversa acontece, parece qual tradutor de programas?",
      opcoes: ["O compilador", "Nenhum dos dois", "O interpretador"],
      correta: 2,
      explicacao: "O interpretador traduz e roda uma parte de cada vez, enquanto o programa acontece.",
    },
    { pergunta: "Quem traduz enquanto roda?", dica: "Pense no intérprete de uma entrevista." },
  ),
  item(
    "interpretador-2",
    "interpretador",
    vitrine("vitrine-rodar-de-novo.exemplo", "Um programa em Python rodando pela segunda vez", "python conta.py (de novo)"),
    {
      pergunta: "Rodando de novo, o interpretador do Python traduz o programa outra vez?",
      opcoes: ["Sim: traduz enquanto roda, toda vez", "Não: guardou o executável", "Só a primeira linha"],
      correta: 0,
      explicacao: "O interpretador não entrega um executável pronto: ele traduz enquanto roda, a cada vez.",
    },
    { pergunta: "O interpretador guarda um programa pronto?", dica: "Ele traduz no caminho, como um intérprete." },
  ),
  item(
    "alto-e-baixo-nivel-1",
    "alto-e-baixo-nivel",
    vitrine("vitrine-degraus.exemplo", "Duas linhas que fazem a mesma soma", "total = preco + frete / 0010 0111"),
    {
      pergunta: "Qual das duas é de baixo nível, mais perto da máquina?",
      opcoes: ["total = preco + frete", "As duas são iguais", "0010 0111"],
      correta: 2,
      explicacao: "Os bits são a linguagem de máquina: o degrau mais baixo da escada.",
    },
    { pergunta: "Qual delas o processador lê sem tradutor?", dica: "Baixo nível é perto da máquina; alto nível, perto da gente." },
  ),
  item(
    "alto-e-baixo-nivel-2",
    "alto-e-baixo-nivel",
    vitrine("vitrine-escada.exemplo", "A escada das linguagens", "bits > assembly > C > Python"),
    {
      pergunta: "Subindo a escada, a linguagem fica mais perto de quem?",
      opcoes: ["Da máquina", "Da gente", "De ninguém"],
      correta: 1,
      explicacao: "Quanto mais alto, mais perto do jeito de pensar da gente. Cada degrau esconde o de baixo.",
    },
    { pergunta: "Python fica no alto ou embaixo?", dica: "Alto nível: a linguagem cuida dos detalhes da máquina." },
  ),
  // Sala 4: por baixo do capô.
  item(
    "memoria-ram-1",
    "memoria-ram",
    vitrine("vitrine-desligar.exemplo", "Um computador que acabou de desligar", "memória: ???"),
    {
      pergunta: "O que acontece com o que estava na memória quando o computador desliga?",
      opcoes: ["Fica guardado para sempre", "Se apaga", "Vai para a internet"],
      correta: 1,
      explicacao: "A memória é rápida, mas esquece quando a energia acaba. Para guardar de vez, existem os arquivos no disco.",
    },
    { pergunta: "Memória ou disco: qual esquece ao desligar?", dica: "A memória guarda o que os programas estão usando agora." },
  ),
  item(
    "memoria-ram-2",
    "memoria-ram",
    vitrine("vitrine-caixas.exemplo", "A memória por dentro", "[0] [1] [2] [3] [4] ..."),
    {
      pergunta: "A memória parece mais com o quê?",
      opcoes: ["Uma fileira de caixas numeradas", "Um rio de bits sem lugar certo", "Uma foto da tela"],
      correta: 0,
      explicacao: "São caixas numeradas, cada uma guardando um valor. O número é o endereço.",
    },
    { pergunta: "Como o computador acha um valor na memória?", dica: "Pelo número da caixa." },
  ),
  item(
    "endereco-de-memoria-1",
    "endereco-de-memoria",
    vitrine("vitrine-etiqueta.exemplo", "Caixa 7, com a etiqueta frete", "[7] frete = 8"),
    {
      pergunta: "Nessa caixa, o que é o 7?",
      opcoes: ["O valor guardado", "O nome da variável", "O endereço da caixa"],
      correta: 2,
      explicacao: "7 é o endereço (onde fica a caixa); 8 é o valor; frete é o nome que a linguagem dá ao endereço.",
    },
    { pergunta: "O número da caixa diz o quê?", dica: "Endereço é onde; valor é o que tem dentro." },
  ),
  item(
    "endereco-de-memoria-2",
    "endereco-de-memoria",
    vitrine("vitrine-apelido.exemplo", "let preco = 12;", "preco mora na caixa 3"),
    {
      pergunta: "Para o computador, o nome preco é...",
      opcoes: ["Um apelido para o endereço 3", "Um texto que ele lê toda vez", "O próprio número 12"],
      correta: 0,
      explicacao: "A variável é um nome para uma caixa. O computador usa o endereço; o nome é para a gente.",
    },
    { pergunta: "Onde o preço mora?", dica: "A variável aponta uma caixa da memória." },
  ),
  item(
    "processador-1",
    "processador",
    vitrine("vitrine-ciclo.exemplo", "O ciclo do processador", "buscar > ? > executar"),
    {
      pergunta: "Qual etapa falta no ciclo, entre buscar e executar?",
      opcoes: ["Desligar", "Entender (decodificar a ordem)", "Imprimir"],
      correta: 1,
      explicacao: "Buscar a ordem, entender o que ela pede e executar. E de novo, bilhões de vezes por segundo.",
    },
    { pergunta: "O que o processador faz com a ordem antes de cumprir?", dica: "Ele precisa saber o que a ordem pede." },
  ),
  item(
    "processador-2",
    "processador",
    vitrine("vitrine-acumulador.exemplo", "PEGA 6 (12), depois SOMA 7 (8)", "acumulador: ?"),
    {
      pergunta: "Depois do PEGA e do SOMA, quanto o acumulador guarda?",
      opcoes: ["8", "12", "20"],
      correta: 2,
      explicacao: "O PEGA põe 12 no acumulador; o SOMA junta o 8: 20.",
    },
    { pergunta: "O que já estava no acumulador antes do SOMA?", dica: "O acumulador segura a conta do momento." },
  ),
  item(
    "sistema-operacional-1",
    "sistema-operacional",
    vitrine("vitrine-tres-programas.exemplo", "Música, navegador e jogo abertos", "1 processador, 3 programas"),
    {
      pergunta: "Quem divide o processador entre os três programas?",
      opcoes: ["O sistema operacional", "O próprio jogo", "O mouse"],
      correta: 0,
      explicacao: "O sistema operacional é o gerente: dá a vez a cada programa, em fatias de tempo, bem rápido.",
    },
    { pergunta: "Quem é o gerente do computador?", dica: "Windows, Android e Linux fazem esse trabalho." },
  ),
  item(
    "sistema-operacional-2",
    "sistema-operacional",
    vitrine("vitrine-engasgo.exemplo", "A música ficou muito tempo sem a vez", "som: tr... tr... trava"),
    {
      pergunta: "Por que a música engasgou?",
      opcoes: ["O fone quebrou", "Ficou tempo demais sem a vez do processador", "A memória ficou cheia de música"],
      correta: 1,
      explicacao: "Quem tem pressa, como a música, precisa da vez com frequência. O gerente cuida disso.",
    },
    { pergunta: "Quanto tempo a música pode ficar sem a vez?", dica: "Pouco: ela toca um pedacinho a cada fatia." },
  ),
  item(
    "sistema-de-arquivos-1",
    "sistema-de-arquivos",
    vitrine("vitrine-caminho.exemplo", "Um caminho de arquivo", "Meu computador / Fotos / praia.jpg"),
    {
      pergunta: "Nesse caminho, praia.jpg mora em qual pasta?",
      opcoes: ["Meu computador", "Fotos", "Em nenhuma"],
      correta: 1,
      explicacao: "O caminho vai da raiz até o arquivo: praia.jpg está dentro de Fotos, que está em Meu computador.",
    },
    { pergunta: "Qual pasta vem logo antes do arquivo?", dica: "O caminho é a trilha da raiz até o arquivo." },
  ),
  item(
    "sistema-de-arquivos-2",
    "sistema-de-arquivos",
    vitrine("vitrine-arvore-de-pastas.exemplo", "Pastas desenhadas como árvore", "raiz > galhos > folhas"),
    {
      pergunta: "Desenhando as pastas como árvore, os arquivos são...",
      opcoes: ["A raiz", "Os galhos", "As folhas, nas pontas"],
      correta: 2,
      explicacao: "A raiz fica no topo, as pastas são galhos e os arquivos são as folhas.",
    },
    { pergunta: "Arquivo pode ter coisa dentro, como pasta?", dica: "As folhas ficam nas pontas." },
  ),
  item(
    "meio-somador-1",
    "meio-somador",
    vitrine("vitrine-somador.exemplo", "Somar 1 + 1 com o meio somador", "soma: ? vai um: ?"),
    {
      pergunta: "Somando 1 + 1, como ficam as duas lâmpadas?",
      opcoes: ["Soma acesa, vai um apagado", "Soma apagada, vai um aceso: 10", "As duas acesas: 11"],
      correta: 1,
      explicacao: "1 + 1 = 2, que em binário é 10: o vai um aceso e a soma apagada.",
    },
    { pergunta: "Como se escreve 2 em binário?", dica: "Dois bits: 1 na casa da frente, 0 na de trás." },
  ),
  item(
    "meio-somador-2",
    "meio-somador",
    vitrine("vitrine-portoes-soma.exemplo", "Dentro do meio somador", "soma = ? / vai um = E"),
    {
      pergunta: "O vai um é um portão E. E a soma, acende quando?",
      opcoes: ["Quando só uma das entradas está ligada", "Sempre", "Quando as duas estão ligadas"],
      correta: 0,
      explicacao: "A soma é o OU exclusivo: acende com uma OU outra, mas NÃO com as duas.",
    },
    { pergunta: "1 + 0 dá quanto? E 1 + 1, na casa de trás?", dica: "Quando as duas ligam, a soma vai para o vai um." },
  ),
  item(
    "realimentacao-1",
    "realimentacao",
    vitrine("vitrine-selo.exemplo", "O botão liga do motor, apertado e solto", "motor: ?"),
    {
      pergunta: "Com o selo (a saída voltando para a entrada), o que o motor faz quando você solta o botão?",
      opcoes: ["Desliga junto", "Continua ligado: o circuito lembrou", "Pisca sem parar"],
      correta: 1,
      explicacao: "A saída volta para a entrada e segura o circuito ligado, até alguém apertar o desliga.",
    },
    { pergunta: "Quem continua mandando corrente depois que você solta?", dica: "A própria saída, que volta para a entrada." },
  ),
  item(
    "realimentacao-2",
    "realimentacao",
    vitrine("vitrine-memoria-de-portoes.exemplo", "Um circuito que guarda um bit", "OU + E + NÃO + fio de volta"),
    {
      pergunta: "Qual peça transforma esses portões numa memória?",
      opcoes: ["O fio que leva a saída de volta para a entrada", "O portão NÃO sozinho", "A lâmpada"],
      correta: 0,
      explicacao: "A realimentação: a saída voltando para a entrada faz o circuito se lembrar do valor.",
    },
    { pergunta: "Sem o fio de volta, o circuito se lembra?", dica: "Lembrar é a saída segurar a si mesma." },
  ),
  // Sala 5: o caminho de um clique.
  item(
    "dns-1",
    "dns",
    vitrine("vitrine-lista-telefonica.exemplo", "padariadobairro.com.br = ?", "nome > endereço"),
    {
      pergunta: "Quem troca o nome do site pelo endereço do servidor?",
      opcoes: ["O roteador de casa", "O próprio site", "O DNS"],
      correta: 2,
      explicacao: "O DNS é a lista telefônica da internet: nome de um lado, endereço do outro.",
    },
    { pergunta: "O navegador sabe o endereço só pelo nome?", dica: "Ele pergunta para uma lista." },
  ),
  item(
    "dns-2",
    "dns",
    vitrine("vitrine-dns-fora.exemplo", "O DNS saiu do ar", "Não é possível acessar esse site"),
    {
      pergunta: "O servidor está funcionando, mas o DNS caiu. O site abre?",
      opcoes: ["Abre normalmente", "Não: o navegador não sabe o endereço", "Abre mais rápido"],
      correta: 1,
      explicacao: "Sem o DNS, o navegador não tem o endereço: nem consegue mandar o pedido.",
    },
    { pergunta: "O que o DNS dá ao navegador?", dica: "Sem endereço, não tem para onde ir." },
  ),
  item(
    "pacote-de-rede-1",
    "pacote-de-rede",
    vitrine("vitrine-pacotes.exemplo", "Uma foto enviada pela internet", "[1/4] [2/4] [3/4] [4/4]"),
    {
      pergunta: "Como a foto viaja pela rede?",
      opcoes: ["Inteira, num pedaço só", "Em pacotes, que se juntam no destino", "Por carta"],
      correta: 1,
      explicacao: "A mensagem é dividida em pacotes, que viajam pela rede e se juntam de novo no destino.",
    },
    { pergunta: "O que quer dizer 1/4, 2/4...?", dica: "Pedacinhos numerados de uma mensagem." },
  ),
  item(
    "pacote-de-rede-2",
    "pacote-de-rede",
    vitrine("vitrine-pulos.exemplo", "O caminho de um pacote", "casa > bairro > cidade > servidor"),
    {
      pergunta: "Cada seta desse caminho é...",
      opcoes: ["Um pulo de roteador em roteador", "Um pedaço da foto", "Um clique do mouse"],
      correta: 0,
      explicacao: "O pacote pula de roteador em roteador, até chegar ao servidor.",
    },
    { pergunta: "Quem passa o pacote adiante em cada parada?", dica: "Os roteadores." },
  ),
  item(
    "roteador-1",
    "roteador",
    vitrine("vitrine-roteador.exemplo", "A caixinha de luzes da sala", "roteador Wi-Fi"),
    {
      pergunta: "O que o roteador de casa faz com os pacotes?",
      opcoes: ["Guarda as fotos", "Desenha a página", "Passa adiante, na direção do destino"],
      correta: 2,
      explicacao: "O roteador recebe o pacote e encaminha para o próximo ponto, até o destino.",
    },
    { pergunta: "Roteador guarda ou passa adiante?", dica: "Ele é a esquina do caminho." },
  ),
  item(
    "roteador-2",
    "roteador",
    vitrine("vitrine-desvio.exemplo", "Um cabo do caminho partiu", "A > X > servidor / A > B > servidor"),
    {
      pergunta: "Se um cabo parte, o que os roteadores fazem?",
      opcoes: ["Acham outro caminho até o destino", "Desistem do pacote", "Esperam o cabo ser consertado"],
      correta: 0,
      explicacao: "A internet tem vários caminhos: os roteadores mandam o pacote por outro.",
    },
    { pergunta: "Tem só um caminho até o servidor?", dica: "A rede é uma teia, não uma linha." },
  ),
  item(
    "front-e-back-1",
    "front-e-back",
    vitrine("vitrine-loja.exemplo", "Uma loja online", "[botão Comprar] / [estoque: 12]"),
    {
      pergunta: "O estoque de 12 peças fica guardado onde?",
      opcoes: ["No back-end, no servidor", "No front-end, no navegador", "No botão"],
      correta: 0,
      explicacao: "Dados guardados e regras ficam no back-end. O front mostra o número na tela.",
    },
    { pergunta: "Se ficasse no navegador, cada cliente veria o quê?", dica: "Back: guarda e confere. Front: mostra e pede." },
  ),
  item(
    "front-e-back-2",
    "front-e-back",
    vitrine("vitrine-animacao.exemplo", "Um menu que abre deslizando", "[ Menu > ]"),
    {
      pergunta: "A animação do menu roda onde?",
      opcoes: ["No servidor", "No banco de dados", "No navegador: é front-end"],
      correta: 2,
      explicacao: "O que aparece e reage na tela roda no navegador: front-end.",
    },
    { pergunta: "Quem desenha a tela?", dica: "O navegador fica na frente de quem usa." },
  ),
  item(
    "cabo-submarino-1",
    "cabo-submarino",
    vitrine("vitrine-oceano.exemplo", "Um vídeo de outro continente", "Brasil ~~~ oceano ~~~ Europa"),
    {
      pergunta: "Por onde passa quase todo esse tráfego entre os continentes?",
      opcoes: ["Por satélite", "Por cabos no fundo do mar", "Por rádio"],
      correta: 1,
      explicacao: "Quase todo o tráfego entre continentes passa por cabos de fibra no fundo do mar.",
    },
    { pergunta: "A internet é uma nuvem no céu?", dica: "Ela é física: cabos de verdade, inclusive no mar." },
  ),
  item(
    "cabo-submarino-2",
    "cabo-submarino",
    vitrine("vitrine-fortaleza.exemplo", "Uma estação de cabo na praia", "cabo > mar > outro continente"),
    {
      pergunta: "Para que serve uma estação de cabo na costa?",
      opcoes: ["Ligar a rede da terra aos cabos submarinos", "Guardar sites", "Medir as ondas"],
      correta: 0,
      explicacao: "Ali os cabos submarinos chegam do mar e se ligam à rede da terra.",
    },
    { pergunta: "De onde os cabos submarinos saem?", dica: "Da praia, de estações na costa." },
  ),
  item(
    "aba-rede-1",
    "aba-rede",
    vitrine("vitrine-f12-rede.exemplo", "F12 aberto na aba Rede, ainda vazia", "Rede (Network): 0 pedidos"),
    {
      pergunta: "A aba Rede está vazia. O que fazer para ela mostrar os pedidos da página?",
      opcoes: ["Fechar o F12", "Recarregar a página com a aba aberta", "Clicar no título"],
      correta: 1,
      explicacao: "A aba anota só o que acontece depois de aberta. Recarregar (F5) faz a página pedir tudo de novo.",
    },
    { pergunta: "Quando a aba começa a anotar?", dica: "Depois de aberta: recarregue." },
  ),
  item(
    "aba-rede-2",
    "aba-rede",
    vitrine("vitrine-cascata.exemplo", "A coluna Tempo da aba Rede", "documento 120 ms / foto 1400 ms / css 60 ms"),
    {
      pergunta: "Qual arquivo deixou a página mais lenta?",
      opcoes: ["O documento", "O CSS", "A foto"],
      correta: 2,
      explicacao: "A foto levou 1400 ms, de longe o maior tempo. Imagem grande é o suspeito de sempre.",
    },
    { pergunta: "Qual número da coluna Tempo é o maior?", dica: "ms quer dizer milissegundos." },
  ),
  item(
    "codigo-de-status-1",
    "codigo-de-status",
    vitrine("vitrine-404.exemplo", "Um pedido na aba Rede", "selo.png | 404"),
    {
      pergunta: "O que quer dizer o 404?",
      opcoes: ["Deu certo", "O servidor não achou o arquivo", "O servidor está muito rápido"],
      correta: 1,
      explicacao: "404 é Not Found: o servidor procurou e não achou. 200 é deu certo; 500, o servidor falhou.",
    },
    { pergunta: "200 é bom ou ruim?", dica: "Números de 400 em diante são problema." },
  ),
  item(
    "codigo-de-status-2",
    "codigo-de-status",
    vitrine("vitrine-500.exemplo", "Um pedido na aba Rede", "agenda | 500"),
    {
      pergunta: "O pedido da agenda voltou com 500. De quem é o problema?",
      opcoes: ["Do servidor, que falhou", "Do mouse", "Do cabo submarino"],
      correta: 0,
      explicacao: "500 é Internal Server Error: o pedido chegou, mas o servidor se atrapalhou para responder.",
    },
    { pergunta: "O pedido chegou ao servidor?", dica: "500 é erro do lado do servidor." },
  ),
  // Sala 6: onde a programação vive.
  item(
    "software-embarcado-1",
    "software-embarcado",
    vitrine("vitrine-micro-ondas.exemplo", "Um micro-ondas", "[ 0:30 ] [Iniciar]"),
    {
      pergunta: "O micro-ondas tem um programa dentro?",
      opcoes: ["Não, só eletricidade", "Só se tiver internet", "Sim: um programa pequeno, embarcado"],
      correta: 2,
      explicacao: "O relógio, o tempo e o bipe são um programa embarcado, que mora dentro do aparelho.",
    },
    { pergunta: "Quem conta os 30 segundos?", dica: "Programa embarcado mora dentro do aparelho." },
  ),
  item(
    "software-embarcado-2",
    "software-embarcado",
    vitrine("vitrine-semaforo.exemplo", "Um semáforo de esquina", "verde > amarelo > vermelho"),
    {
      pergunta: "O programa do semáforo roda onde?",
      opcoes: ["Dentro do próprio semáforo (ou da caixa ao lado)", "No celular de quem passa", "Num site"],
      correta: 0,
      explicacao: "É software embarcado: roda num computadorzinho junto do aparelho, sem tela.",
    },
    { pergunta: "O semáforo tem tela e teclado?", dica: "Embarcado: o programa vai junto com o aparelho." },
  ),
  item(
    "carreiras-em-programacao-1",
    "carreiras-em-programacao",
    vitrine("vitrine-previsao-onibus.exemplo", "O painel do ponto: ônibus em 4 min", "[ 4 min ]"),
    {
      pergunta: "Quem costuma cuidar dessa previsão?",
      opcoes: ["Gente de dados", "Gente de front-end", "Ninguém: é sorte"],
      correta: 0,
      explicacao: "Transformar muitas viagens antigas numa previsão boa é trabalho de dados.",
    },
    { pergunta: "A previsão vem de onde?", dica: "Muitos números de antes viram um palpite bom." },
  ),
  item(
    "carreiras-em-programacao-2",
    "carreiras-em-programacao",
    vitrine("vitrine-senha-bloqueada.exemplo", "Cartão bloqueado depois de três senhas erradas", "BLOQUEADO"),
    {
      pergunta: "Pensar em como impedir um golpista é trabalho de qual área?",
      opcoes: ["Front-end", "Segurança", "Dados"],
      correta: 1,
      explicacao: "Segurança pensa no que alguém mal-intencionado tentaria, e fecha a porta antes.",
    },
    { pergunta: "Quem pensa como o golpista, para se defender?", dica: "Uma das profissões da tela de Profissões." },
  ),
];
